In [5]:
# Python code that reduces a Matrix into its Row Echelon Form, test Singularity of the matrix and finds rank.

# importing numpy library
import numpy as np

# Function : Reduces the matrix row by row until Row Echelon Form is achieved

def row_reduce(A):
    B = np.array(A,dtype=np.float_) # Taking B as a copy of A, because we are going to alter it's values.
    reduce_matrix(B)
    rank = np.linalg.matrix_rank(B) # To find rank of matrix
    print('The Rank is:',rank)
    print('The Row Echelon Form is:')
    return B

def reduce_matrix(A):
    
    # To check whether the first element of Row Zero is 0, if 0 then swap lower rows until we can make it non-zero.
    # If we fail to make it non-zero, matrix is singular.  
    
    if A[0,0] == 0:
        A[[0, 1]] = A[[1, 0]]
    if A[0,0] == 0:
        A[[0, 1]] = A[[1, 0]]       # Swapping to initial position
        A[[0, 2]] = A[[2, 0]]
    if A[0,0] == 0:
        print('The Matrix is Singular')
        A[[0, 2]] = A[[2, 0]]       # Swapping to initial position
        
        
        # To check whether the second element in the row zero is 0, if 0 then swap lower rows until we can make it non-zero.
        
        if A[0,1] == 0:           
            A[[0, 1]] = A[[1, 0]]
        if A[0,1] == 0:
            A[[0, 1]] = A[[1, 0]]   # Swapping to initial position
            A[[0, 2]] = A[[2, 0]]
        if A[0,1] == 0:
            A[[0, 2]] = A[[2, 0]]   # Swapping to initial position
        
            # To check whether the third element in the row zero is 0, if 0 then swap lower rows until we can make it non-zero.
            
            if A[0,2] == 0:
                A[[0, 1]] = A[[1, 0]]
            if A[0,2] == 0:
                A[[0, 2]] = A[[2, 0]]
            if A[0,2] == 0:
                print('The Matrix is a Null Matrix')   # If all the elements are 0.                
  
            # If third element in the row zero is non-zero
            # Reducing Column two
            
            else:    
                A[1] = A[1] - (A[1,2]/A[0,2]) * A[0] 
                A[2] = A[2] - (A[2,2]/A[0,2]) * A[0]
            return A    
            exit()
            
        # If second element in the row zero is non-zero
        # Reducing Column one
        
        else:
            A[1] = A[1] -(A[1,1]/A[0,1]) * A[0]
            A[2] = A[2] -(A[2,1]/A[0,1]) * A[0]
        if A[1,2] != 0:
            A[2] = A[2] -(A[2,2]/A[1,2]) * A[1]
        
        return A
        exit()
        
    # If first element in the row zero is non-zero
    # Reducing Column zero  
    
    else:
        A[1] = A[1] - (A[1,0]/A[0,0]) * A[0]
        A[2] = A[2] - (A[2,0]/A[0,0]) * A[0]
        
        # To check whether the second element of row one is 0, if 0 then swap lower row to make it non-zero.
        
        if A[1,1] == 0:
            A[[1, 2]] = A[[2, 1]]
        
        if A[1,1] == 0:
            A[[1, 2]] = A[[2, 1]]         # Swapping to initial position
            
            if A[1,2] == 0:               # To check whether the third element of row one is 0, if 0 then swap lower row to make it non-zero.
                A[[1, 2]] = A[[2, 1]]   
    
            A[2] = A[2] - (A[2,2]/A[1,2]) * A[1]
        
        # If second element in the row one is non-zero
        # Reducing Column one
        
        else:
            
            A[2] = A[2] - (A[2,1]/A[1,1]) * A[1]
    return A

print('Enter 3x3 Matrix:')
elements = list(map(int, input().split()))  
  
# Printing the matrix given by the user 

A = np.array(elements).reshape(3,3)  
print(A) 

row_reduce(A)

Enter 3x3 Matrix:
3 2 5 8 0 2 2 0 6
[[3 2 5]
 [8 0 2]
 [2 0 6]]
The Rank is: 3
The Row Echelon Form is:


array([[  3.        ,   2.        ,   5.        ],
       [  0.        ,  -5.33333333, -11.33333333],
       [  0.        ,   0.        ,   5.5       ]])